apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  uri: bW9uZ29kYjovL21vbmdvOjI3MDE3L2Zvb2RkZWxpdmVyeQ== # mongodb://mongo:27017/fooddelivery
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  secret: eW91cl9qd3Rfc2VjcmV0 # your_jwt_secret
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  secret-key: eW91cl9zdHJpcGVfc2VjcmV0X2tleQ== # your_stripe_secret_key
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
type: Opaque
data:
  host: eW91cl9zbXRwX2hvc3Q= # your_smtp_host
  user: eW91cl9zbXRwX3VzZXI= # your_smtp_user
  password: eW91cl9zbXRwX3Bhc3N3b3Jk # your_smtp_password
