apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: restaurant-service
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  ports:
    - port: 3003
      targetPort: 3003
  selector:
    app: order-service
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  ports:
    - port: 3004
      targetPort: 3004
  selector:
    app: delivery-service
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  ports:
    - port: 3005
      targetPort: 3005
  selector:
    app: payment-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  ports:
    - port: 3006
      targetPort: 3006
  selector:
    app: notification-service
