services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Matheesha
      - MONGO_INITDB_ROOT_PASSWORD=Matheesha
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:alpine
    command: redis-server --requirepass admin123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb+srv://Matheesha:Matheesha@cluster0.xqfraot.mongodb.net/
      - REDIS_URL=redis://:admin123@redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb+srv://Matheesha:Matheesha@cluster0.xqfraot.mongodb.net/
      - REDIS_URL=redis://:admin123@redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  restaurant-service:
    build: ./restaurant-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb+srv://Matheesha:Matheesha@cluster0.xqfraot.mongodb.net/
      - REDIS_URL=redis://:admin123@redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - MONGODB_URI=mongodb+srv://Matheesha:Matheesha@cluster0.xqfraot.mongodb.net/
      - REDIS_URL=redis://:admin123@redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  delivery-service:
    build: ./delivery-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - MONGODB_URI=mongodb+srv://Matheesha:Matheesha@cluster0.xqfraot.mongodb.net/
      - REDIS_URL=redis://:admin123@redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  payment-service:
    build: ./payment-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - MONGODB_URI=mongodb+srv://Matheesha:Matheesha@cluster0.xqfraot.mongodb.net/
      - REDIS_URL=redis://:admin123@redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development
      - PORT=3006
      - MONGODB_URI=mongodb+srv://Matheesha:Matheesha@cluster0.xqfraot.mongodb.net/
      - REDIS_URL=redis://:admin123@redis:6379
    depends_on:
      - redis
    networks:
      - app-network

volumes:
  mongodb_data:
  redis_data:

networks:
  app-network:
    driver: bridge
