services:
  user-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGO_URI=mongodb+srv://Matheesha:Matheesha@cluster0.xqfraot.mongodb.net/serviceA_db?retryWrites=true&w=majority
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRE=30d
      - CORS_ORIGIN=${CORS_ORIGIN}
    # Remove depends_on since we're not using local MongoDB
